### PR TITLE
fix(null): manage null value in JSON

### LINKED ISSUE #3: Explicit NULL value in JSON are not managed
Cannot reset a field to null.

### PR DESCRIPTION
**Pull request by jroucou**
Closes #3

### CODE REVIEW

File: request_test.go [hunk 1]
```diff
@@ -1278,3 +1278,73 @@ func TestUnmarshalNestedStructSlice(t *testing.T) {
...
+				},
+			},
+		},
+	}
+
+	data, err := json.Marshal(person)
+	if err != nil {
+		t.Fatal(err)
+	}
+	fmt.Println(string(data))
```
Comment (denouche) [inline request_test.go]: remove this println plz

**Review by denouche — CHANGES_REQUESTED** [review]

**Review by rlespinasse — APPROVED** [review]

**Review by denouche — APPROVED** [review]
